complexity:
  LongMethod:
    threshold: 30
  TooManyFunctions:
    excludes: ['**/test/**']
    thresholdInClasses: 20
    thresholdInFiles: 20

style:
  MaxLineLength:
    maxLineLength: 140
  WildcardImport:
    active: true

naming:
  ClassNaming:
    classPattern: '[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
