INSERT INTO lessons (course_id, sort_order, title_ko, lesson_type, content, estimated_seconds) VALUES
('c1000000-0000-0000-0000-000000000002', 1, '운영체제란?', 'flashcard', '{"cards":[{"front":"운영체제(OS)란 무엇인가?","back":"하드웨어와 사용자 사이에서 중재자 역할을 하는 시스템 소프트웨어로, 컴퓨터 자원을 관리하고 응용 프로그램 실행 환경을 제공한다.","hint":null},{"front":"운영체제의 핵심 역할 4가지는?","back":"① 프로세스 관리 ② 메모리 관리 ③ 파일 시스템 관리 ④ 입출력(I/O) 장치 관리","hint":"자원 관리 측면에서 생각해보세요."},{"front":"커널(Kernel)이란?","back":"운영체제의 핵심 구성 요소로, 하드웨어와 직접 상호작용하며 프로세스·메모리·장치를 관리하는 상주 프로그램이다.","hint":null},{"front":"운영체제의 목표 두 가지는?","back":"① 편의성: 사용자가 컴퓨터를 편리하게 사용할 수 있도록 환경 제공 ② 효율성: 시스템 자원을 효율적으로 관리하여 성능 극대화","hint":null},{"front":"시스템 콜(System Call)이란?","back":"사용자 프로그램이 운영체제의 서비스를 요청하기 위해 커널에 접근하는 인터페이스. 예) open(), read(), write(), fork()","hint":"유저 모드에서 커널 모드로 전환하는 방법을 생각해보세요."}]}', 420),

('c1000000-0000-0000-0000-000000000002', 2, '커널과 유저 모드', 'quiz', '{"questions":[{"question":"커널 모드(Kernel Mode)와 유저 모드(User Mode)를 구분하는 주된 이유는?","code":null,"options":["CPU 사용률을 높이기 위해","시스템 자원을 보호하고 잘못된 접근을 방지하기 위해","메모리 속도를 향상시키기 위해","멀티코어 처리를 지원하기 위해"],"correct_index":1,"explanation":"유저 모드에서는 하드웨어 자원에 직접 접근할 수 없으며, 운영체제 서비스가 필요할 때 시스템 콜을 통해 커널 모드로 전환함으로써 자원을 보호한다."},{"question":"다음 중 시스템 콜(System Call) 호출 시 발생하는 모드 전환의 순서로 올바른 것은?","code":null,"options":["유저 모드 → 커널 모드 → 유저 모드","커널 모드 → 유저 모드 → 커널 모드","유저 모드 → 유저 모드 → 커널 모드","커널 모드 → 커널 모드 → 유저 모드"],"correct_index":0,"explanation":"사용자 프로그램은 유저 모드에서 실행되다가 시스템 콜을 요청하면 커널 모드로 전환되어 서비스를 수행한 후 다시 유저 모드로 복귀한다."},{"question":"모드 비트(Mode Bit)가 0일 때 의미하는 것은?","code":null,"options":["유저 모드","슬립 모드","커널 모드","인터럽트 모드"],"correct_index":2,"explanation":"모드 비트가 0이면 커널 모드, 1이면 유저 모드를 나타낸다. 커널 모드에서는 모든 명령어 실행이 허용된다."},{"question":"다음 중 커널 모드에서만 실행 가능한 명령어는?","code":null,"options":["사칙연산","문자열 비교","I/O 장치 접근 명령","배열 정렬"],"correct_index":2,"explanation":"I/O 장치 접근, 인터럽트 처리, 메모리 관리 등은 특권 명령어로 커널 모드에서만 실행 가능하다. 사칙연산이나 문자열 비교는 유저 모드에서도 실행된다."},{"question":"인터럽트(Interrupt)와 트랩(Trap)의 차이점은?","code":null,"options":["인터럽트는 소프트웨어가 발생, 트랩은 하드웨어가 발생","인터럽트는 하드웨어가 발생, 트랩은 소프트웨어(시스템 콜 등)가 발생","둘 다 동일한 개념","인터럽트는 커널에서, 트랩은 유저에서 처리"],"correct_index":1,"explanation":"인터럽트는 타이머, I/O 완료 등 하드웨어에 의해 발생하고, 트랩은 시스템 콜 호출이나 예외(오류) 등 소프트웨어에 의해 발생한다."}]}', 480),

('c1000000-0000-0000-0000-000000000002', 3, '프로세스 개념', 'flashcard', '{"cards":[{"front":"프로그램(Program)과 프로세스(Process)의 차이는?","back":"프로그램은 디스크에 저장된 실행 파일(수동적 개체)이고, 프로세스는 메모리에 올라와 실행 중인 프로그램(능동적 개체)이다.","hint":null},{"front":"PCB(Process Control Block)란?","back":"운영체제가 각 프로세스를 관리하기 위해 유지하는 자료구조. PID, 프로세스 상태, 프로그램 카운터, 레지스터, 메모리 정보, 스케줄링 정보 등을 포함한다.","hint":null},{"front":"프로세스의 메모리 구조 4가지는?","back":"① 텍스트(코드) 영역: 실행 코드 ② 데이터 영역: 전역/정적 변수 ③ 힙(Heap): 동적 할당 메모리 ④ 스택(Stack): 함수 호출 정보, 지역 변수","hint":"위→아래 방향으로 스택, 아래→위 방향으로 힙이 증가합니다."},{"front":"프로세스 ID(PID)란?","back":"운영체제가 각 프로세스를 식별하기 위해 부여하는 고유한 정수 값. 프로세스 생성 시 할당되며 종료 시 반환된다.","hint":null},{"front":"독립 프로세스와 협력 프로세스의 차이는?","back":"독립 프로세스는 다른 프로세스와 데이터를 공유하지 않으며 영향을 주고받지 않는다. 협력 프로세스는 다른 프로세스와 데이터를 공유하거나 상호 영향을 미친다. IPC가 필요하다.","hint":null}]}', 420),

('c1000000-0000-0000-0000-000000000002', 4, '프로세스 상태', 'quiz', '{"questions":[{"question":"프로세스가 CPU를 할당받아 명령어를 실행하고 있는 상태는?","code":null,"options":["New","Ready","Running","Waiting"],"correct_index":2,"explanation":"Running 상태는 프로세스가 CPU를 점유하여 실행 중인 상태이다. 단일 CPU 시스템에서는 한 번에 하나의 프로세스만 Running 상태를 가진다."},{"question":"프로세스가 I/O 완료를 기다리고 있는 상태는?","code":null,"options":["New","Ready","Running","Waiting(Blocked)"],"correct_index":3,"explanation":"Waiting(Blocked) 상태는 프로세스가 I/O 완료, 이벤트 발생 등 특정 조건이 충족될 때까지 대기하는 상태이다."},{"question":"Ready 상태에서 Running 상태로의 전환은 무엇이 수행하는가?","code":null,"options":["인터럽트","스케줄러(Dispatcher)","시스템 콜","타이머"],"correct_index":1,"explanation":"CPU 스케줄러(디스패처)가 Ready 큐에서 프로세스를 선택하여 CPU를 할당하면 Ready → Running 상태로 전환된다."},{"question":"다음 중 프로세스 상태 전환으로 올바르지 않은 것은?","code":null,"options":["New → Ready","Running → Waiting","Waiting → Running","Terminated → 제거"],"correct_index":2,"explanation":"Waiting 상태의 프로세스는 I/O 완료 등 이벤트 발생 시 Ready 상태로 전환된다. Waiting에서 바로 Running으로 전환되지 않는다."},{"question":"타임 퀀텀(Time Quantum)이 만료되었을 때 Running 프로세스의 상태 전환은?","code":null,"options":["Running → Terminated","Running → Waiting","Running → Ready","Running → New"],"correct_index":2,"explanation":"타임 퀀텀(할당 시간)이 만료되면 타이머 인터럽트가 발생하여 현재 Running 프로세스는 Ready 상태로 전환되고 다른 프로세스에게 CPU가 할당된다."}]}', 480),

('c1000000-0000-0000-0000-000000000002', 5, '프로세스 생성', 'fill_blank', '{"questions":[{"question":"다음은 Unix/Linux에서 자식 프로세스를 생성하는 코드이다. 빈칸에 알맞은 시스템 콜은?","code":"#include <unistd.h>\nint main() {\n    pid_t pid = ___();\n    if (pid == 0) {\n        // 자식 프로세스\n    } else {\n        // 부모 프로세스\n    }\n    return 0;\n}","options":["exec","fork","wait","clone"],"correct_index":1,"explanation":"fork()는 현재 프로세스(부모)를 복제하여 자식 프로세스를 생성한다. 부모에게는 자식의 PID가, 자식에게는 0이 반환된다."},{"question":"다음 코드에서 자식 프로세스가 새로운 프로그램을 실행하도록 빈칸에 알맞은 함수는?","code":"pid_t pid = fork();\nif (pid == 0) {\n    ___(\"/bin/ls\", \"ls\", \"-l\", NULL);\n    // 새 프로그램으로 대체\n}","options":["fork","wait","execl","printf"],"correct_index":2,"explanation":"execl()은 exec 계열 함수 중 하나로, 현재 프로세스 이미지를 새 프로그램으로 완전히 대체한다. exec 호출 이후의 코드는 실행되지 않는다."},{"question":"부모 프로세스가 자식 프로세스의 종료를 기다리는 시스템 콜은?","code":"pid_t pid = fork();\nif (pid > 0) {\n    int status;\n    ___(NULL);\n    printf(\"자식 종료 완료\\n\");
