INSERT INTO lessons (course_id, sort_order, title_ko, lesson_type, content, estimated_seconds) VALUES
('c1000000-0000-0000-0000-000000000004', 1, 'RDBMS 개념', 'flashcard', '{
  "cards": [
    {"front": "RDBMS란 무엇인가?", "back": "관계형 데이터베이스 관리 시스템(Relational Database Management System)으로, 데이터를 테이블(표) 형태로 저장하고 관리하는 소프트웨어 시스템이다. Oracle, MySQL, PostgreSQL, SQL Server 등이 대표적인 예이다.", "hint": "Relational Database Management System"},
    {"front": "테이블, 행, 열의 관계는?", "back": "테이블(Table)은 데이터를 저장하는 2차원 구조이다. 행(Row/Record)은 테이블의 가로 한 줄로 하나의 데이터 항목을 나타낸다. 열(Column/Attribute)은 테이블의 세로 한 줄로 데이터의 속성(필드)을 나타낸다.", "hint": "행 = 레코드, 열 = 속성"},
    {"front": "스키마(Schema)란?", "back": "데이터베이스의 구조와 제약 조건을 정의한 설계도이다. 테이블의 이름, 열 이름, 데이터 타입, 제약 조건 등 데이터베이스의 전체적인 논리적 구조를 기술한다. 외부 스키마, 개념 스키마, 내부 스키마의 3단계로 구분된다.", "hint": "데이터베이스의 설계도"},
    {"front": "DBMS의 주요 역할 4가지는?", "back": "① 데이터 정의(DDL): 테이블 생성·수정·삭제\n② 데이터 조작(DML): 데이터 삽입·조회·수정·삭제\n③ 데이터 제어(DCL): 접근 권한 및 보안 관리\n④ 트랜잭션 관리: 데이터 일관성 및 무결성 보장", "hint": "DDL, DML, DCL, 트랜잭션"},
    {"front": "관계형 모델에서 도메인(Domain)이란?", "back": "각 열(속성)이 가질 수 있는 값의 집합이다. 예를 들어 나이 열의 도메인은 0~150의 정수이고, 성별 열의 도메인은 {''남'', ''여''}일 수 있다. 도메인을 벗어난 값은 저장할 수 없다.", "hint": "열이 가질 수 있는 유효한 값의 범위"}
  ]
}', 420),

('c1000000-0000-0000-0000-000000000004', 2, '기본키와 외래키', 'quiz', '{
  "questions": [
    {"question": "기본키(Primary Key)의 특성으로 올바르지 않은 것은?", "code": null, "options": ["유일성: 테이블 내에서 중복된 값을 가질 수 없다", "최소성: 꼭 필요한 최소한의 속성으로 구성된다", "NULL 허용: 기본키 열은 NULL 값을 가질 수 있다", "불변성: 기본키 값은 자주 변경되지 않아야 한다"], "correct_index": 2, "explanation": "기본키는 반드시 NOT NULL이어야 한다. NULL 값은 기본키로 사용할 수 없으며, 이는 개체 무결성(Entity Integrity) 제약 조건이다."},
    {"question": "다음 SQL에서 외래키(Foreign Key) 제약 조건이 올바르게 설정된 것은?", "code": "-- 부모 테이블\nCREATE TABLE departments (\n  dept_id INT PRIMARY KEY,\n  dept_name VARCHAR(50)\n);\n\n-- 자식 테이블 후보들", "options": ["CREATE TABLE employees (emp_id INT PRIMARY KEY, dept_id INT);", "CREATE TABLE employees (emp_id INT PRIMARY KEY, dept_id INT REFERENCES departments(dept_id));", "CREATE TABLE employees (emp_id INT PRIMARY KEY, dept_id INT REFERENCES employees(emp_id));", "CREATE TABLE employees (emp_id INT FOREIGN KEY, dept_id INT);"], "correct_index": 1, "explanation": "외래키는 REFERENCES 키워드를 사용하여 참조할 부모 테이블과 열을 지정한다. 외래키는 반드시 부모 테이블의 기본키(또는 유일키)를 참조해야 한다."},
    {"question": "참조 무결성(Referential Integrity)에 대한 설명으로 올바른 것은?", "code": null, "options": ["자식 테이블의 외래키 값은 NULL이 될 수 없다", "부모 테이블에 존재하지 않는 값을 자식 테이블의 외래키로 삽입할 수 없다", "부모 테이블의 기본키 값은 반드시 자식 테이블에 존재해야 한다", "외래키가 설정된 열은 중복 값을 가질 수 없다"], "correct_index": 1, "explanation": "참조 무결성은 자식 테이블의 외래키 값이 반드시 부모 테이블의 기본키로 존재하거나 NULL이어야 한다는 제약이다. 부모에 없는 값을 자식에 삽입하면 오류가 발생한다."},
    {"question": "ON DELETE CASCADE 옵션의 동작으로 올바른 것은?", "code": "CREATE TABLE orders (\n  order_id INT PRIMARY KEY,\n  customer_id INT,\n  FOREIGN KEY (customer_id)\n    REFERENCES customers(customer_id)\n    ON DELETE CASCADE\n);", "options": ["고객 삭제 시 해당 고객의 주문도 자동으로 삭제된다", "주문 삭제 시 해당 고객도 자동으로 삭제된다", "고객 삭제 시 주문의 customer_id가 NULL로 변경된다", "고객이 주문을 가지고 있으면 고객 삭제가 불가능하다"], "correct_index": 0, "explanation": "ON DELETE CASCADE는 부모 레코드(고객)가 삭제될 때 해당 레코드를 참조하는 자식 레코드(주문)도 자동으로 함께 삭제되는 옵션이다."},
    {"question": "복합 기본키(Composite Primary Key)를 사용하기에 적합한 테이블은?", "code": null, "options": ["학생 테이블 (학번, 이름, 학과)", "수강 테이블 (학번, 과목코드, 성적) — 학번+과목코드 조합", "교수 테이블 (교수번호, 이름, 부서)", "과목 테이블 (과목코드, 과목명, 학점)"], "correct_index": 1, "explanation": "수강 테이블에서 한 학생이 같은 과목을 중복 수강할 수 없으므로 (학번, 과목코드)의 조합이 유일성을 보장한다. 이처럼 두 개 이상의 열을 합쳐 기본키로 사용하는 것을 복합 기본키라 한다."}
  ]
}', 600),

('c1000000-0000-0000-0000-000000000004', 3, 'SQL SELECT 기초', 'fill_blank', '{
  "questions": [
    {"question": "employees 테이블에서 salary가 3000 이상인 직원의 이름과 급여를 조회하는 쿼리의 빈칸을 채우세요.", "code": "SELECT name, salary\n___ employees\n___ salary >= 3000;", "options": ["FROM / WHERE", "INTO / HAVING", "FROM / HAVING", "IN / WHERE"], "correct_index": 0, "explanation": "SELECT 문의 기본 구조는 SELECT 열 FROM 테이블 WHERE 조건이다. FROM은 조회할 테이블을 지정하고, WHERE는 필터링 조건을 지정한다."},
    {"question": "products 테이블의 모든 열을 조회할 때 빈칸에 들어갈 내용은?", "code": "SELECT ___\nFROM products;", "options": ["* (별표)", "ALL", "EVERY", "DISTINCT"], "correct_index": 0, "explanation": "SELECT * 는 테이블의 모든 열을 조회하는 와일드카드이다. 실무에서는 필요한 열만 명시하는 것이 성능상 유리하다."},
    {"question": "중복을 제거하고 부서 목록만 조회하려면 빈칸에 무엇을 넣어야 하나요?", "code": "SELECT ___ department\nFROM employees;", "options": ["DISTINCT", "UNIQUE", "DIFFERENT", "ONLY"], "correct_index": 0, "explanation": "DISTINCT 키워드는 조회 결과에서 중복된 행을 제거한다. SELECT DISTINCT column_name FROM table_name 형태로 사용한다."},
    {"question": "조회 결과를 salary 기준으로 내림차순 정렬하는 쿼리의 빈칸은?", "code": "SELECT name, salary\nFROM employees\nORDER BY salary ___;", "options": ["DESC", "ASC", "DESCEND", "DOWN"], "correct_index": 0, "explanation": "ORDER BY 절에서 DESC는 내림차순(큰 값 → 작은 값), ASC는 오름차순(작은 값 → 큰 값) 정렬을 지정한다. 기본값은 ASC이다."},
    {"question": "상위 5개의 행만 조회하려면 빈칸에 무엇이 들어가야 하나요? (PostgreSQL 기준)", "code": "SELECT name, salary\nFROM employees\nORDER BY salary DESC\n___ 5;", "options": ["LIMIT", "TOP", "ROWNUM <=", "FETCH FIRST"], "correct_index": 0, "explanation": "PostgreSQL, MySQL에서는 LIMIT N 을 사용하여 조회 행 수를 제한한다. SQL Server에서는 TOP N, Oracle에서는 ROWNUM 또는 FETCH FIRST N ROWS ONLY를 사용한다."}
  ]
}', 540),

('c1000000-0000-0000-0000-000000000004', 4, 'INSERT/UPDATE/DELETE', 'quiz', '{
  "questions": [
    {"question": "다음 INSERT 문의 실행 결과로 올바른 것은?", "code": "INSERT INTO students (student_id, name, grade)\nVALUES (101, ''김철수'', 3);", "options": ["students 테이블에 새 행이 추가된다", "students 테이블의 기존 행이 수정된다", "students 테이블에서 행이 삭제된다", "students 테이블의 구조가 변경된다"], "correct_index": 0, "explanation": "INSERT INTO ... VALUES ... 문은 테이블에 새로운 행(레코드)을 삽입하는 DML(Data Manipulation Language) 명령이다. 열 목록과 값의 수 및 순서가 일치해야 한다."},
    {"question": "모든 직원의 급여를 10% 인상하는 올바른 UPDATE 문은?", "code": null, "options": ["UPDATE employees SET salary = salary * 1.1;", "UPDATE employees WHERE salary = salary * 1.1;", "MODIFY employees SET salary = salary * 1.1;", "ALTER employees SET salary = salary * 1.1;"], "correct_index": 0, "explanation": "UPDATE 문의 구조는 UPDATE 테이블 SET 열=값 [WHERE 조건]이다. WHERE 절을 생략하면 테이블의 모든 행이 업데이트된다. MODIFY나 ALTER는 잘못된 문법이다."},
    {"question": "특정 조건의 데이터만 삭제하는 올바른 DELETE 문은?", "code": null, "options": ["DELETE FROM orders WHERE order_date < ''2023-01-01'';", "DELETE orders WHERE order_date < ''2023-01-01'';", "REMOVE FROM orders WHERE order_date < ''2023-01-01'';", "DROP FROM orders WHERE order_date < ''2023-01-01'';"], "correct_index": 0, "explanation": "DELETE FROM 테이블 WHERE 조건 구문을 사용한다. WHERE 절 없이 DELETE FROM 테이블을 실행하면 모든 행이 삭제된다. DROP은 테이블 자체를 삭제하는 DDL 명령이다."},
    {"question": "다음 중 DML(Data Manipulation Language)에 해당하지 않는 것은?", "code": null, "options": ["INSERT", "SELECT", "TRUNCATE", "UPDATE"], "correct_index": 2, "explanation": "TRUNCATE는 테이블의 모든 데이터를 삭제하지만 DDL(Data Definition Language)로 분류된다. INSERT, UPDATE, DELETE, SELECT는 DML이다. TRUNCATE는 롤백이 불가능하며 DELETE보다 빠르다."},
    {"question": "다음 UPDATE 문에서 문제점은?", "code": "UPDATE products\nSET price = 0;", "options": ["SET 키워드가 잘못되었다", "WHERE 절이 없어 모든 상품 가격이 0이 된다", "테이블명이 잘못되었다", "price 열 이름이 잘못되었다"], "correct_index": 1, "explanation": "WHERE 절 없는 UPDATE는 테이블의 모든 행을 수정한다. 실수로 실행하면 전체 데이터가 변경되는 치명적인 오류가 발생한다. 항상 WHERE 조건을 확인한 후 UPDATE를 실행해야 한다."}
  ]
}', 600),

('c1000000-0000-0000-0000-000000000004', 5, 'WHERE 조건절', 'fill_blank', '{
  "questions": [
    {"question": "나이가 20세 이상 30세 이하인 학생을 조회하는 조건절의 빈칸을 채우세요.", "code": "SELECT * FROM students\nWHERE age ___ 20 ___ 30;", "options": ["BETWEEN / AND", "FROM / TO", ">= / <=", "IN / AND"], "correct_index": 0, "explanation": "BETWEEN A AND B는 A 이상 B 이하의 범위를 나타내는 조건이다. WHERE age >= 20 AND age <= 30과 동일하지만 더 간결하게 표현할 수 있다."},
    {"question": "이름이 ''김''으로 시작하는 고객을 검색하는 LIKE 패턴은?", "code": "SELECT * FROM customers\nWHERE name LIKE ___;", "options": ["''김%''", "''%김''", "''김_''", "''*김*''"], "correct_index": 0, "explanation": "LIKE에서 %는 0개 이상의 임의 문자를 의미하는 와일드카드이다. ''김%''는 ''김''으로 시작하는 모든 문자열, ''%김''은 ''김''으로 끝나는 문자열, ''%김%''는 ''김''을 포함하는 문자열을 검색한다."},
    {"question": "부서가 ''개발'', ''기획'', ''마케팅'' 중 하나인 직원을 조회하는 조건의 빈칸은?", "code": "SELECT * FROM employees\nWHERE department ___ (''개발'', ''기획'', ''마케팅'');", "options": ["IN", "LIKE", "BETWEEN", "EXISTS"], "correct_index": 0, "explanation": "IN 연산자는 값이 목록 중 하나와 일치하는지 검사한다. WHERE department = ''개발'' OR department = ''기획'' OR department = ''마케팅'' 과 동일하지만 IN을 사용하면 더 간결하다."},
    {"question": "salary가 5000 초과이면서 department가 ''영업''인 조건을 표현하는 논리 연산자는?", "code": "SELECT * FROM employees\nWHERE salary > 5000 ___ department = ''영업'';", "options": ["AND", "OR", "NOT", "XOR"], "correct_index": 0, "explanation": "AND 연산자는 두 조건이 모두 참일 때 행을 반환한다. OR은 둘 중 하나라도 참이면 반환한다. 복잡한 조건에서는 괄호를 사용하여 우선순위를 명확히 해야 한다."},
    {"question": "이메일이 NULL인 고객을 조회하는 올바른 조건은?", "code": "SELECT * FROM customers\nWHERE email ___ NULL;", "options": ["IS", "=", "LIKE", "IN"], "correct_index": 0, "explanation": "NULL 값 비교는 반드시 IS NULL 또는 IS NOT NULL을 사용해야 한다. WHERE email = NULL은 항상 거짓을 반환하며 동작하지 않는다. NULL은 ''알 수 없음''을 의미하므로 일반 비교 연산자를 사용할 수 없다."}
  ]
}', 540),

('c1000000-0000-0000-0000-000000000004', 6, 'JOIN 개념', 'flashcard', '{
  "cards": [
    {"front": "INNER JOIN이란?", "back": "두 테이블에서 조인 조건을 만족하는 행만 반환한다. 양쪽 테이블 모두에 매칭되는 데이터만 결과에 포함되며, 한쪽에만 있는 데이터는 제외된다.\n\n예: SELECT * FROM A INNER JOIN B ON A.id = B.a_id", "hint": "교집합"},
    {"front": "LEFT (OUTER) JOIN이란?", "back": "왼쪽 테이블의 모든 행을 반환하고, 오른쪽 테이블에서 조건을 만족하는 행을 매칭한다. 오른쪽에 매칭되는 행이 없으면 NULL로 채워진다.\n\n예: 고객 테이블 LEFT JOIN 주문 테이블 → 주문이 없는 고객도 포함", "hint": "왼쪽 테이블 전체 유지"},
    {"front": "RIGHT (OUTER) JOIN이란?", "back": "오른쪽 테이블의 모든 행을 반환하고, 왼쪽 테이블에서 조건을 만족하는 행을 매칭한다. 왼쪽에 매칭이 없으면 NULL로 채워진다. LEFT JOIN의 테이블 순서를 바꾼 것과 동일한 결과를 얻을 수 있다.", "hint": "오른쪽 테이블 전체 유지"},
    {"front": "FULL OUTER JOIN과 CROSS JOIN의 차이는?", "back": "FULL OUTER JOIN: 양쪽 테이블의 모든 행을 포함하며, 매칭되지 않는 쪽은 NULL로 채움. 두 테이블의 합집합.\n\nCROSS JOIN: 두 테이블의 모든 행의 조합을 반환 (카티션 곱). A가 3행, B가 4행이면 결과는 12행. 조인 조건 없음.", "hint": "FULL=합집합, CROSS=곱집합"},
    {"front": "SELF JOIN이란?", "back": "동일한 테이블을 두 번 참조하여 조인하는 방식이다. 테이블에 별칭(alias)을 다르게 부여하여 사용한다.\n\n예: 직원 테이블에서 각 직원의 관리자 이름을 조회할 때\nSELECT e.name, m.name AS 관리자\nFROM employees e JOIN employees m ON e.manager_id = m.emp_id", "hint": "같은 테이블끼리 조인"}
  ]
}', 480),

('c1000000-0000-0000-0000-000000000004', 7, 'JOIN 실전', 'quiz', '{
  "questions": [
    {"question": "다음 INNER JOIN 결과로 반환되는 행의 수는?", "code": "-- customers 테이블: id=1,2,3\n-- orders 테이블: customer_id=1,1,2\n-- (customer_id=3인 주문 없음)\n\nSELECT c.name, o.order_id\nFROM customers c\nINNER JOIN orders o ON c.id = o.customer_id;", "options": ["3행", "2행", "4행", "1행"], "correct_index": 0, "explanation": "INNER JOIN은 양쪽에 매칭되는 행만 반환한다. customer_id=1인 주문 2건 + customer_id=2인 주문 1건 = 총 3행이 반환된다. customer_id=3인 고객은 주문이 없으므로 제외된다."},
    {"question": "LEFT JOIN으로 변경할 경우 반환되는 행의 수는?", "code": "-- customers 테이블: id=1,2,3\n-- orders 테이블: customer_id=1,1,2\n\nSELECT c.name, o.order_id\nFROM customers c\nLEFT JOIN orders o ON c.id = o.customer_id;", "options": ["4행", "3행", "2행", "6행"], "correct_index": 0, "explanation": "LEFT JOIN은 왼쪽(customers) 테이블의 모든 행을 포함한다. id=1 고객(2건) + id=2 고객(1건) + id=3 고객(주문 없어 NULL, 1건) = 총 4행이 반환된다."},
    {"question": "다음 쿼리에서 별칭(alias) 사용의 목적은?", "code": "SELECT e.name AS 직원명,\n       d.dept_name AS 부서명\nFROM employees e\nJOIN departments d ON e.dept_id = d.dept_id;", "options": ["쿼리를 짧게 작성하고 결과 열 이름을 명확하게 표시하기 위해", "JOIN 성능을 향상시키기 위해", "WHERE 조건 없이 전체 데이터를 조회하기 위해", "중복 데이터를 제거하기 위해"], "correct_index": 0, "explanation": "테이블 별칭(e, d)은 긴 테이블 이름을 짧게 참조할 수 있게 해준다. 열 별칭(AS 직원명)은 결과 헤더를 원하는 이름으로 표시한다. 특히 여러 테이블 조인 시 어느 테이블의 열인지 명확히 구분할 수 있다."},
    {"question": "세 테이블을 조인할 때 올바른 쿼리 구조는?", "code": null, "options": ["FROM A JOIN B ON A.id=B.a_id JOIN C ON B.id=C.b_id", "FROM A, B, C JOIN ON A.id=B.id=C.id", "FROM A JOIN (B JOIN C)", "JOIN A, B, C ON A.id=B.id AND B.id=C.id"], "correct_index": 0, "explanation": "여러 테이블을 조인할 때는 JOIN ... ON 절을 순서대로 추가한다. 앞선 조인 결과에 다음 테이블을 계속 조인하는 방식이며, 각 JOIN마다 ON 조건을 명시해야 한다."},
    {"question": "다음 쿼리에서 NULL이 반환되는 상황은?", "code": "SELECT c.name, o.order_id\nFROM customers c\nLEFT JOIN orders o ON c.id = o.customer_id\nWHERE o.order_id IS NULL;", "options": ["주문이 한 번도 없는 고객만 조회된다", "주문이 있는 고객만 조회된다", "모든 고객과 모든 주문이 조회된다", "주문 테이블이 비어있을 때만 결과가 나온다"], "correct_index": 0, "explanation": "LEFT JOIN에서 오른쪽 테이블에 매칭 행이 없으면 그 열들은 NULL이 된다. WHERE o.order_id IS NULL 조건을 추가하면 주문이 없는 고객만 필터링된다. 이는 ''한 번도 주문하지 않은 고객 찾기'' 패턴으로 자주 사용된다."}
  ]
}', 660),

('c1000000-0000-0000-0000-000000000004', 8, '서브쿼리', 'reading', '{
  "questions": [
    {"question": "다음 서브쿼리의 실행 결과는?", "code": "SELECT name, salary\nFROM employees\nWHERE salary > (\n  SELECT AVG(salary)\n  FROM employees\n);", "options": ["평균 급여보다 높은 급여를 받는 직원 목록이 반환된다", "가장 높은 급여를 받는 직원 1명이 반환된다", "평균 급여와 동일한 급여를 받는 직원이 반환된다", "모든 직원의 급여 평균이 반환된다"], "correct_index": 0, "explanation": "WHERE 절의 서브쿼리는 먼저 실행되어 단일 값(평균 급여)을 반환한다. 외부 쿼리는 이 값보다 salary가 큰 직원을 필터링한다. 이처럼 WHERE 절에 서브쿼리를 사용하면 집계 결과를 필터 조건으로 활용할 수 있다."},
    {"question": "FROM 절 서브쿼리(인라인 뷰)에 대한 설명으로 올바른 것은?", "code": "SELECT dept_name, avg_sal\nFROM (\n  SELECT d.dept_name,\n         AVG(e.salary) AS avg_sal\n  FROM employees e\n  JOIN departments d ON e.dept_id = d.dept_id\n  GROUP BY d.dept_name\n) AS dept_avg\nWHERE avg_sal > 4000;
INSERT INTO lessons (course_id, sort_order, title_ko, lesson_type, content, estimated_seconds) VALUES
('c1000000-0000-0000-0000-000000000004', 1, 'RDBMS 개념', 'flashcard', '{"cards":[{"front":"RDBMS란 무엇인가?","back":"관계형 데이터베이스 관리 시스템(Relational Database Management System). 데이터를 테이블(행과 열) 형태로 저장하고, SQL을 통해 관리하는 소프트웨어 시스템이다. 예: MySQL, PostgreSQL, Oracle.","hint":null},{"front":"테이블, 행, 열의 차이는?","back":"테이블(Table): 관련 데이터의 집합. 행(Row/Record/Tuple): 하나의 데이터 항목. 열(Column/Attribute/Field): 데이터의 속성. 예: students 테이블에서 한 학생 정보가 행, 이름·나이 등이 열이다.","hint":"스프레드시트와 비교해보자"},{"front":"스키마(Schema)란?","back":"데이터베이스의 구조와 제약 조건을 정의한 설계도. 테이블 이름, 열 이름, 데이터 타입, 제약 조건 등을 포함한다. CREATE TABLE 문으로 정의하며, 데이터 자체가 아닌 데이터의 틀이다.","hint":null},{"front":"DBMS의 주요 역할 4가지는?","back":"1) 데이터 저장 및 검색 관리\n2) 데이터 무결성 및 보안 유지\n3) 동시성 제어 (여러 사용자 동시 접근)\n4) 트랜잭션 관리 및 장애 복구","hint":"무결성, 보안, 동시성, 복구"},{"front":"DDL, DML, DCL의 차이는?","back":"DDL(Data Definition Language): 구조 정의 - CREATE, ALTER, DROP\nDML(Data Manipulation Language): 데이터 조작 - SELECT, INSERT, UPDATE, DELETE\nDCL(Data Control Language): 권한 제어 - GRANT, REVOKE","hint":null}]}', 600),

('c1000000-0000-0000-0000-000000000004', 2, '기본키와 외래키', 'quiz', '{"questions":[{"question":"기본키(Primary Key)의 특성으로 올바른 것은?","code":null,"options":["NULL 값을 허용하며 중복될 수 없다","NULL 값을 허용하지 않으며 테이블 내에서 유일해야 한다","중복 값을 허용하지만 NULL은 가능하다","한 테이블에 여러 개의 기본키를 설정할 수 있다"],"correct_index":1,"explanation":"기본키는 NOT NULL + UNIQUE 조건을 동시에 만족해야 한다. 각 행을 유일하게 식별하는 역할을 하므로 NULL이나 중복 값은 허용되지 않는다."},{"question":"다음 테이블 정의에서 외래키 제약 조건이 올바르게 설정된 것은?","code":"-- orders 테이블 (customer_id가 customers 테이블 참조)\nA) CREATE TABLE orders (\n  order_id INT PRIMARY KEY,\n  customer_id INT\n);\n\nB) CREATE TABLE orders (\n  order_id INT PRIMARY KEY,\n  customer_id INT REFERENCES customers(customer_id)\n);\n\nC) CREATE TABLE orders (\n  order_id INT PRIMARY KEY,\n  customer_id INT UNIQUE\n);\n\nD) CREATE TABLE orders (\n  order_id INT PRIMARY KEY,\n  customer_id INT NOT NULL\n);","options":["A","B","C","D"],"correct_index":1,"explanation":"REFERENCES 키워드를 사용하여 참조할 테이블과 열을 명시해야 외래키 제약 조건이 설정된다. 나머지는 단순히 NOT NULL이나 UNIQUE만 설정할 뿐 외래키가 아니다."},{"question":"참조 무결성(Referential Integrity)이 위반되는 경우는?","code":null,"options":["부모 테이블에 존재하는 값을 외래키로 삽입할 때","자식 테이블의 행을 삭제할 때","부모 테이블에 없는 값을 외래키로 삽입하려 할 때","부모 테이블에 새로운 행을 추가할 때"],"correct_index":2,"explanation":"참조 무결성은 외래키 값이 반드시 참조하는 테이블의 기본키에 존재해야 한다는 규칙이다. 존재하지 않는 값을 외래키로 삽입하면 위반된다."},{"question":"ON DELETE CASCADE 옵션의 동작으로 올바른 것은?","code":"CREATE TABLE orders (\n  order_id INT PRIMARY KEY,\n  customer_id INT REFERENCES customers(customer_id)\n    ON DELETE CASCADE\n);","options":["부모 행 삭제 시 자식 행도 자동으로 삭제된다","부모 행 삭제 시 자식 행의 외래키가 NULL로 변경된다","부모 행 삭제를 금지한다","자식 행 삭제 시 부모 행도 삭제된다"],"correct_index":0,"explanation":"ON DELETE CASCADE는 부모 테이블의 행이 삭제될 때 해당 행을 참조하는 자식 테이블의 행도 연쇄적으로 삭제하는 옵션이다."},{"question":"복합 기본키(Composite Primary Key)에 대한 설명으로 올바른 것은?","code":"CREATE TABLE enrollment (\n  student_id INT,\n  course_id INT,\n  enrolled_at DATE,\n  PRIMARY KEY (student_id, course_id)\n);","options":["student_id와 course_id 각각이 유일해야 한다","student_id와 course_id의 조합이 유일해야 한다","두 열 모두 NULL을 허용한다","이 테이블에는 다른 제약 조건을 추가할 수 없다"],"correct_index":1,"explanation":"복합 기본키는 두 개 이상의 열을 조합하여 행을 유일하게 식별한다. 각 열은 개별적으로 중복될 수 있지만, 조합은 반드시 유일해야 한다."}]}', 720),

('c1000000-0000-0000-0000-000000000004', 3, 'SQL SELECT 기초', 'fill_blank', '{"questions":[{"question":"students 테이블에서 모든 열을 조회하는 SQL을 완성하세요.","code":"___ * ___ students;","options":["SELECT / FROM","FETCH / IN","GET / FROM","SELECT / WHERE"],"correct_index":0,"explanation":"기본 조회 문법은 SELECT 열이름 FROM 테이블명 이다. 모든 열을 조회할 때는 * 를 사용한다."},{"question":"나이가 20세 이상인 학생의 이름만 조회하는 SQL을 완성하세요.","code":"SELECT name FROM students ___ age ___ 20;","options":["WHERE / >=","HAVING / >=","WHERE / =>","FILTER / >="],"correct_index":0,"explanation":"WHERE 절은 조회 조건을 지정한다. 크거나 같다는 >= 연산자를 사용한다. HAVING은 GROUP BY와 함께 집계 조건에만 사용된다."},{"question":"결과를 나이 기준 오름차순으로 정렬하는 SQL을 완성하세요.","code":"SELECT name, age FROM students\nORDER BY age ___;","options":["ASC","DESC","UP","ASCENDING"],"correct_index":0,"explanation":"ORDER BY 기본값은 ASC(오름차순)이지만 명시적으로 ASC를 쓸 수 있다. DESC는 내림차순이다."},{"question":"중복을 제거하고 학과명만 조회하는 SQL을 완성하세요.","code":"SELECT ___ department FROM students;","options":["DISTINCT","UNIQUE","DIFFERENT","NODUPLICATE"],"correct_index":0,"explanation":"DISTINCT 키워드는 조회 결과에서 중복 행을 제거한다. SELECT DISTINCT 열이름 FROM 테이블명 형태로 사용한다."},{"question":"조회 결과를 5행으로 제한하는 SQL을 완성하세요.","code":"SELECT * FROM students\nORDER BY student_id\n___ 5;","options":["LIMIT","TOP","ROWNUM","FETCH"],"correct_index":0,"explanation":"MySQL, PostgreSQL에서는 LIMIT을 사용한다. SQL Server는 TOP, Oracle은 ROWNUM 또는 FETCH FIRST를 사용한다. 표준 SQL은 FETCH FIRST N ROWS ONLY이다."}]}', 600),

('c1000000-0000-0000-0000-000000000004', 4, 'INSERT/UPDATE/DELETE', 'quiz', '{"questions":[{"question":"다음 INSERT 문에서 문법 오류가 있는 것은?","code":"A) INSERT INTO students (name, age) VALUES (''김철수'', 20);\nB) INSERT INTO students VALUES (1, ''김철수'', 20, ''컴퓨터공학'');\nC) INSERT INTO students (name, age) VALUES ''김철수'', 20;\nD) INSERT INTO students (name) VALUES (''이영희'');","options":["A","B","C","D"],"correct_index":2,"explanation":"INSERT 문에서 VALUES 뒤에 오는 값 목록은 반드시 괄호로 감싸야 한다. C는 괄호가 없어 문법 오류다."},{"question":"학번이 1001인 학생의 나이를 21로 변경하는 올바른 SQL은?","code":null,"options":["UPDATE students SET age = 21 WHERE student_id = 1001;","MODIFY students SET age = 21 WHERE student_id = 1001;","UPDATE students WHERE student_id = 1001 SET age = 21;","ALTER students SET age = 21 WHERE student_id = 1001;"],"correct_index":0,"explanation":"UPDATE 문법은 UPDATE 테이블명 SET 열=값 WHERE 조건 순서이다. MODIFY나 ALTER는 데이터 변경이 아닌 구조 변경에 사용되는 키워드다."},{"question":"WHERE 절 없이 DELETE를 실행하면 어떻게 되는가?","code":"DELETE FROM students;","options":["오류가 발생하여 실행되지 않는다","첫 번째 행만 삭제된다","테이블의 모든 행이 삭제된다","테이블 구조까지 삭제된다"],"correct_index":2,"explanation":"WHERE 절이 없는 DELETE는 테이블의 모든 행을 삭제한다. 테이블 구조는 유지된다. 구조까지 삭제하려면 DROP TABLE을 사용해야 한다."},{"question":"다음 중 여러 행을 한 번에 삽입하는 올바른 SQL은?","code":null,"options":["INSERT INTO students VALUES (1,''김철수'',20), (2,''이영희'',21);","INSERT MULTIPLE INTO students VALUES (1,''김철수'',20),(2,''이영희'',21);","INSERT INTO students VALUES (1,''김철수'',20) AND (2,''이영희'',21);","INSERT INTO students (1,''김철수'',20), (2,''이영희'',21);"],"correct_index":0,"explanation":"다중 행 삽입은 VALUES 절에 쉼표로 구분하여 여러 값 목록을 나열한다. 이는 여러 번 INSERT하는 것보다 성능상 효율적이다."},{"question":"UPDATE 시 여러 열을 동시에 변경하는 올바른 방법은?","code":null,"options":["UPDATE students SET age=22 SET grade=''A'' WHERE id=1;","UPDATE students SET age=22, grade=''A'' WHERE id=1;","UPDATE students SET (age=22, grade=''A'') WHERE id=1;","UPDATE students SET age=22 AND grade=''A'' WHERE id=1;"],"correct_index":1,"explanation":"UPDATE에서 여러 열을 변경할 때는 SET 절에서 쉼표로 구분하여 나열한다. SET을 여러 번 쓰거나 AND로 연결하는 것은 잘못된 문법이다."}]}', 720),

('c1000000-0000-0000-0000-000000000004', 5, 'WHERE 조건절', 'fill_blank', '{"questions":[{"question":"이름이 ''김''으로 시작하는 학생을 조회하는 SQL을 완성하세요.","code":"SELECT * FROM students WHERE name ___ ''김%'';","options":["LIKE","=","CONTAINS","MATCH"],"correct_index":0,"explanation":"LIKE는 패턴 매칭에 사용된다. %는 0개 이상의 임의 문자를 의미한다. ''김%''는 ''김''으로 시작하는 모든 문자열과 일치한다."},{"question":"나이가 20세 이상 25세 이하인 학생을 조회하는 SQL을 완성하세요.","code":"SELECT * FROM students WHERE age ___ 20 ___ 25;","options":["BETWEEN / AND","FROM / TO",">= / <=","IN / AND"],"correct_index":0,"explanation":"BETWEEN A AND B는 A 이상 B 이하의 범위를 조건으로 지정한다. 양쪽 경계값을 포함하며 숫자, 날짜, 문자열에 모두 사용 가능하다."},{"question":"학과가 ''컴퓨터공학'' 또는 ''소프트웨어'' 또는 ''전자공학''인 학생을 조회하는 SQL을 완성하세요.","code":"SELECT * FROM students\nWHERE department ___ (''컴퓨터공학'', ''소프트웨어'', ''전자공학'');","options":["IN","=","LIKE","ANY"],"correct_index":0,"explanation":"IN 연산자는 값이 목록 안에 포함되는지 확인한다. OR 조건을 여러 번 쓰는 것과 동일하지만 훨씬 간결하다."},{"question":"나이가 20세 이상이고 학과가 ''컴퓨터공학''인 학생을 조회하는 SQL을 완성하세요.","code":"SELECT * FROM students\nWHERE age >= 20 ___ department = ''컴퓨터공학'';","options":["AND","OR","BUT","ALSO"],"correct_index":0,"explanation":"AND 연산자는 두 조건이 모두 참일 때만 행을 반환한다. OR은 둘 중 하나만 참이어도 반환한다. AND가 OR보다 연산 우선순위가 높다."},{"question":"학과 정보가 없는(NULL인) 학생을 조회하는 SQL을 완성하세요.","code":"SELECT * FROM students WHERE department ___ ___;","options":["IS / NULL","= / NULL","EQUALS / NULL","IS / EMPTY"],"correct_index":0,"explanation":"NULL 값 비교는 반드시 IS NULL 또는 IS NOT NULL을 사용해야 한다. = NULL은 항상 거짓을 반환하므로 NULL 비교에 = 연산자를 사용해서는 안 된다."}]}', 660),

('c1000000-0000-0000-0000-000000000004', 6, 'JOIN 개념', 'flashcard', '{"cards":[{"front":"INNER JOIN이란?","back":"두 테이블에서 조인 조건을 만족하는 행만 반환한다. 양쪽 테이블에 모두 존재하는 데이터만 결과에 포함된다.\n\n예:\nSELECT * FROM orders o\nINNER JOIN customers c ON o.customer_id = c.customer_id;","hint":"교집합"},{"front":"LEFT (OUTER) JOIN이란?","back":"왼쪽 테이블의 모든 행을 반환하고, 오른쪽 테이블에서 조건을 만족하는 행을 붙인다. 오른쪽에 매칭 데이터가 없으면 NULL로 채운다.\n\n예: 주문이 없는 고객도 포함하여 조회할 때 사용.","hint":"왼쪽 테이블 기준"},{"front":"RIGHT (OUTER) JOIN이란?","back":"오른쪽 테이블의 모든 행을 반환하고, 왼쪽 테이블에서 조건을 만족하는 행을 붙인다. 왼쪽에 매칭 데이터가 없으면 NULL로 채운다.\n\nLEFT JOIN에서 테이블 순서를 바꾼 것과 동일하다.","hint":"오른쪽 테이블 기준"},{"front":"FULL OUTER JOIN이란?","back":"양쪽 테이블의 모든 행을 반환한다. 한쪽에만 존재하는 행은 반대쪽을 NULL로 채운다. LEFT JOIN과 RIGHT JOIN의 합집합과 같다.\n\nMySQL은 FULL OUTER JOIN을 직접 지원하지 않아 UNION으로 구현한다.","hint":"합집합"},{"front":"CROSS JOIN이란?","back":"두 테이블의 모든 행을 조합한 카테시안 곱(Cartesian Product)을 반환한다. 조인 조건이 없으며, 결과 행 수 = 왼쪽 행 수 × 오른쪽 행 수.\n\n예: A 테이블 3행 × B 테이블 4행 = 12행 반환.","hint":"카테시안 곱"}]}', 660),

('c1000000-0000-0000-0000-000000000004', 7, 'JOIN 실전', 'quiz', '{"questions":[{"question":"다음 두 테이블에 INNER JOIN을 수행한 결과 행 수는?","code":"-- customers 테이블\ncustomer_id | name\n------------|------\n1           | 김철수\n2           | 이영희\n3           | 박민준\n\n-- orders 테이블\norder_id | customer_id\n---------|------------\n101      | 1\n102      | 1\n103      | 2\n\nSELECT * FROM customers c\nINNER JOIN orders o ON c.customer_id = o.customer_id;","options":["2행","3행","4행","6행"],"correct_index":1,"explanation":"INNER JOIN은 조건을 만족하는 행만 반환한다. customer_id 1은 2번, customer_id 2는 1번 매칭되어 총 3행이 반환된다. customer_id 3은 orders에 없으므로 제외된다."},{"question":"위 두 테이블에 LEFT JOIN을 수행한 결과 행 수는?","code":"SELECT * FROM customers c\nLEFT JOIN orders o ON c.customer_id = o.customer_id;","options":["3행","4행","5행","6행"],"correct_index":1,"explanation":"LEFT JOIN은 왼쪽(customers)의 모든 행을 반환한다. customer_id 1→2행, customer_id 2→1행, customer_id 3→주문 없으므로 NULL로 1행. 총 4행이 반환된다."},{"question":"다음 쿼리에서 주문이 없는 고객만 조회하려면 빈칸에 무엇이 들어가야 하는가?","code":"SELECT c.* FROM customers c\nLEFT JOIN orders o ON c.customer_id = o.customer_id\nWHERE o.order_id ___;","options":["IS NULL","= 0","NOT EXISTS","IS NOT NULL"],"correct_index":0,"explanation":"LEFT JOIN 후 오른쪽 테이블의 키 컬럼이 NULL인 행은 매칭이 없는 행이다. 따라서 IS NULL 조건으로 주문이 없는 고객만 필터링할 수 있다."},{"question":"SELF JOIN을 사용해야 하는 대표적인 상황은?","code":"-- employees 테이블\nemployee_id | name   | manager_id\n------------|--------|----------\n1           | 김사장 | NULL\n2           | 이부장 | 1\n3           | 박대리 | 2","options":["두 개의 서로 다른 테이블을 조인할 때","같은 테이블 내에서 행 간 관계를 조회할 때","테이블의 모든 행을 복제할 때","외래키가 없는 테이블을 조인할 때"],"correct_index":1,"explanation":"SELF JOIN은 같은 테이블을 두 번 참조하여 행 간 관계를 표현할 때 사용한다. 직원-상사 관계처럼 같은 테이블 내 계층 구조를 조회할 때 유용하다."},{"question":"3개 테이블을 조인하는 올바른 SQL 구조는?","code":null,"options":["SELECT * FROM A JOIN B ON A.id=B.id JOIN C ON B.id=C.id;","SELECT * FROM A, B JOIN C ON A.id=B.id=C.id;","SELECT * FROM A JOIN (B JOIN C);","SELECT * FROM A JOIN B JOIN C ON A.id=B.id=C.id;"],"correct_index":0,"explanation":"여러 테이블 조인은 JOIN...ON을 연달아 작성한다. 각 JOIN마다 해당 조인 조건을 ON 절에 명시하면 된다."}]}', 780),

('c1000000-0000-0000-0000-000000000004', 8, '서브쿼리', 'reading', '{"questions":[{"question":"다음 서브쿼리의 실행 결과로 반환되는 학생은?","code":"-- students 테이블\nstudent_id | name   | dept_id | score\n-----------|--------|---------|------\n1          | 김철수 | 10      | 85\n2          | 이영희 | 20      | 92\n3          | 박민준 | 10      | 78\n4          | 최유진 | 30      | 88\n\nSELECT name FROM students\nWHERE score > (SELECT AVG(score) FROM students);","options":["김철수, 이영희","이영희, 최유진","김철수, 박민준","이영희만"],"correct_index":1,"explanation":"서브쿼리 AVG(score) = (85+92+78+88)/4 = 85.75이다. 85.75보다 큰 점수는 이영희(92)와 최유진(88)이므로 두 학생이 반환된다."},{"question":"FROM 절 서브쿼리(인라인 뷰)의 용도로 가장 적절한 것은?","code":"SELECT dept_name, avg_score\nFROM (\n  SELECT dept_id, AVG(score) AS avg_score\n  FROM students\n  GROUP BY dept_id\n) AS dept_avg\nJOIN departments ON dept_avg.dept_id = departments.dept_id;","options":["단일 값을 반환하여 WHERE 조건에 사용한다","집계된 중간 결과를 임시 테이블처럼 사용한다","두 테이블의 공통 열을 자동으로 조인한다","NULL 값을 자동으로 제거한다"],"correct_index":1,"explanation":"FROM 절 서브쿼리(인라인 뷰)는 집계나 변환이 필요한 중간 결과를 임시 테이블처럼 만들어 외부 쿼리에서 사용한다. 별칭(AS)을 반드시 지정해야 한다."},{"question":"EXISTS 서브쿼리와 IN 서브쿼리의 차이로 올바른 것은?","code":"-- IN 방식\nSELECT * FROM customers\nWHERE customer_id IN (SELECT customer_id FROM orders);\n\n-- EXISTS 방식\nSELECT * FROM customers c\nWHERE EXISTS (\n  SELECT 1 FROM orders o\n  WHERE o.customer_id = c.customer_id\n);","options":["IN은 항상 EXISTS보다 빠르다","EXISTS는 조건을 만족하는 행이 하나라도 있으면 즉시 탐색을 중단한다","EXISTS는 서브쿼리의 반환값을 실제로 사용한다","IN은 NULL 값을 자동으로 처리한다"],"correct_index":1,"explanation":"EXISTS는 조건을 만족하는 행이 하나라도 발견되면 즉시 탐색을 멈춘다(short-circuit). 반면 IN은 서브쿼리의 전체 결과를 먼저 구한 후 비교한다. 서브쿼리 결과가 큰 경우 EXISTS가 더 효율적일 수 있다."},{"question":"상관 서브쿼리(Correlated Subquery)의 특징으로 올바른 것은?","code":"SELECT name, score\nFROM students s1\nWHERE score > (\n  SELECT AVG(score)\n  FROM students s2\n  WHERE s2.dept_id = s1.dept_id  -- 외부 쿼리 참조\n);","options":["서브쿼리가 외부 쿼리와 독립적으로 한 번만 실행된다","외부 쿼리의 각 행마다 서브쿼리가 반복 실행된다","항상 단일 값을 반환해야 한다","FROM 절에서만 사용 가능하다"],"correct_index":1,"explanation":"상관 서브쿼리는 외부 쿼리의 현재 행 값을 참조한다. 따라서 외부 쿼리의 행마다 서브쿼리가 재실행된다. 이 예시는 각 학생의 소속 학과 평균 점수와 비교하여 학과 평균 이상인 학생을 조회한다."}]}', 780),

('c1000000-0000-0000-0000-000000000004', 9, 'GROUP BY와 HAVING', 'fill_blank', '{"questions":[{"question":"학과별 학생 수를 조회하는 SQL을 완성하세요.","code":"SELECT department, ___(student_id) AS student_count\nFROM students\n___ BY department;","options":["COUNT / GROUP","SUM / GROUP","COUNT / ORDER","AVG / GROUP"],"correct_index":0,"explanation":"COUNT() 함수는 행 수를 집계한다. GROUP BY는 지정한 열의 값이 같은 행들을 하나의 그룹으로 묶는다. SELECT에 집계 함수가 아닌 열은 반드시 GROUP BY에 포함해야 한다."},{"question":"학과별 평균 점수가 80점 이상인 학과만 조회하는 SQL을 완성하세요.","code":"SELECT department, AVG(score) AS avg_score\nFROM students\nGROUP BY department\n___ AVG(score) >= 80;","options":["HAVING","WHERE","FILTER","AND"],"correct_index":0,"explanation":"HAVING은 GROUP BY로 집계된 결과에 조건을 적용한다. WHERE는 집계 전 행 단위 필터링에 사용하며 집계 함수를 직접 쓸 수 없다. 집계 함수 조건은 반드시 HAVING을 사용해야 한다."},{"question":"전체 학생의 점수 합계를 구하는 SQL을 완성하세요.","code":"SELECT ___(score) AS total_score FROM students;","options":["SUM","TOTAL","ADD","AGGREGATE"],"correct_index":0,"explanation":"SUM() 함수는 수치 열의 합계를 반환한다. NULL 값은 무시된다. 집계 함수에는 COUNT, SUM, AVG, MAX, MIN이 있다."},{"question":"학과별 최고 점수와 최저 점수를 함께 조회하는 SQL을 완성하세요.","code":"SELECT department,\n       ___(score) AS highest,\n       ___(score) AS lowest\nFROM students\nGROUP BY department;","options":["MAX / MIN","HIGHEST / LOWEST","TOP / BOTTOM","UPPER / LOWER"],"correct_index":0,"explanation":"MAX()는 그룹 내 최댓값, MIN()은 최솟값을 반환한다. 두 함수 모두 숫자, 문자열, 날짜 타입에 모두 사용 가능하다."},{"question":"WHERE와 HAVING을 함께 사용하는 SQL을 완성하세요.","code":"SELECT department, COUNT(*) AS cnt\nFROM students\n___ score >= 60       -- 집계 전 필터\nGROUP BY department\n___ COUNT(*) >= 5;    -- 집계 후 필터","options":["WHERE / HAVING","HAVING / WHERE","WHERE / WHERE","HAVING / HAVING"],"correct_index":0,"explanation":"WHERE는 GROUP BY 전에 행을 필터링하고, HAVING은 GROUP BY 후 집계 결과를 필터링한다. 실행 순서는 WHERE → GROUP BY → HAVING → SELECT → ORDER BY이다."}]}', 720),

('c1000000-0000-0000-0000-000000000004', 10, '정규화 개념', 'flashcard', '{"cards":[{"front":"데이터베이스 이상현상(Anomaly)이란?","back":"정규화가 되지 않은 테이블에서 발생하는 문제:\n1) 삽입 이상: 불필요한 데이터를 함께 삽입해야 하는 문제\n2) 삭제 이상: 특정 데이터 삭제 시 다른 필요한 데이터도 같이 삭제되는 문제\n3) 갱신 이상: 중복된 데이터 중 일부만 수정되어 데이터 불일치가 발생하는 문제","hint":"삽입/삭제/갱신"},{"front":"함수적 종속(Functional Dependency)이란?","back":"속성 A의 값이 결정되면 속성 B의 값도 유일하게 결정될 때 ''B는 A에 함수적으로 종속''된다고 하며 A → B로 표기한다.\n\n예: 학번 → 학생이름 (학번이 정해지면 이름이 하나로 결정됨)\n\nA를 결정자(Determinant), B를 종속자라 한다.","hint":"A가 정해지면 B가 하나로 정해짐"},{"front":"부분 함수적 종속 vs 완전 함수적 종속","back":"완전 함수적 종속: 기본키 전체에 종속 (복합키의 모든 속성이 필요)\n\n부분 함수적 종속: 기본키의 일부에만 종속\n\n예: 기본키가 (학번, 과목코드)일 때\n- 점수 → 완전 종속 (학번+과목코드 모두 필요)\n- 학생이름 → 학번에만 부분 종속","hint":"복합키와 관련"},{"front":"이행적 함수적 종속(Transitive Dependency)이란?","back":"A → B이고 B → C이면 A → C가 성립하는 관계.\n\n예:\n학번 → 학과코드 → 학과장이름\n학번이 학과장이름을 이행적으로 결정함.\n\n이행적 종속은 3NF 위반의 원인이 된다.","hint":"A→B→C"},{"front":"정규화(Normalization)의 목적은?","back":"1) 데이터 중복 최소화\n2) 이상현상 방지\n3) 데이터 무결성 향상\n4) 테이블을 더 작고 잘 조직된 단위로 분해\n\n단, 과도한 정규화는 JOIN 연산 증가로 성능 저하를 초래할 수 있으므로 역정규화(Denormalization)를 적절히 고려한다.","hint":null}]}', 660),

('c1000000-0000-0000-0000-000000000004', 11, '1NF~3NF', 'quiz', '{"questions":[{"question":"다음 테이블이 1NF를 위반하는 이유는?","code":"학번 | 이름   | 수강과목\n-----|--------|-------------------\n1001 | 김철수 | 데이터베이스, 알고리즘\n1002 | 이영희 | 운영체제","options":["기본키가 없기 때문이다","수강과목 열에 다중 값이 저장되어 있기 때문이다","이름 열에 중복 값이 있기 때문이다","테이블에 열이 너무 적기 때문이다"],"correct_index":1,"explanation":"1NF(제1정규형)는 모든 속성 값이 원자값(Atomic Value)이어야 한다. ''데이터베이스, 알고리즘''처럼 하나의 셀에 여러 값이 들어가면 1NF를 위반한다."},{"question":"다음 테이블이 2NF를 위반하는 이유는? (기본키: 학번+과목코드)","code":"학번 | 과목코드 | 점수 | 학생이름\n-----|----------|------|--------\n1001 | CS101    | 85   | 김철수\n1001 | CS102    | 92   | 김철수\n1002 | CS101    | 78   | 이영희","options":["점수가 기본키 전체에 종속되지 않기 때문이다","학생이름이 학번에만 부분 함수 종속되기 때문이다","과목코드에 중복 값이 있기 때문이다","기본키 설정이 잘못되었기 때문이다"],"correct_index":1,"explanation":"2NF는 1NF를 만족하고, 기본키의 일부에만 종속(부분 함수 종속)되는 속성이 없어야 한다. 학생이름은 학번+과목코드 전체가 아닌 학번에만 종속되므로 부분 종속이 발생하여 2NF 위반이다."},{"question":"다음 테이블이 3NF를 위반하는 이유는?","code":"학번 | 학과코드 | 학과장\n-----|----------|------\n1001 | CS       | 김교수\n1002 | EE       | 이교수\n1003 | CS       | 김교수","options":["학번→학과코드 종속이 없기 때문이다","학과장이 학번을 통해 이행적으로 결정되기 때문이다","학과코드에 중복이 있기 때문이다","기본키가 학번 하나이기 때문이다"],"correct_index":1,"explanation":"3NF는 2NF를 만족하고, 이행적 함수 종속이 없어야 한다. 학번→학과코드→학과장 관계에서 학과장이 기본키인 학번에 이행적으로 종속되므로 3NF를 위반한다."},{"question":"2NF 위반 테이블을 올바르게 분해한 결과는?","code":"-- 원래 테이블 (학번+과목코드가 기본키)\n학번 | 과목코드 | 점수 | 학생이름","options":["(학번, 과목코드, 점수, 학생이름) 하나의 테이블 유지","(학번, 학생이름) + (학번, 과목코드, 점수) 두 테이블로 분해","(과목코드, 점수) + (학번, 학생이름, 과목코드) 두 테이블로 분해","(학번, 과목코드) + (학생이름, 점수) 두 테이블로 분해"],"correct_index":1,"explanation":"부분 종속을 제거하려면 학번에만 종속되는 학생이름을 별도 테이블로 분리한다. 결과: 학생 테이블(학번, 학생이름)과 수강 테이블(학번, 과목코드, 점수)로 분해한다."},{"question":"다음 중 제2정규형(2NF)의 전제 조건은?","code":null,"options":["제3정규형을 만족해야 한다","제1정규형을 먼저 만족해야 한다","BCNF를 만족해야 한다","복합 기본키가 반드시 존재해야 한다"],"correct_index":1,"explanation":"정규화는 단계적으로 진행된다. 2NF는 1NF를 전제로 하고, 3NF는 2NF를 전제로 한다. 단일 기본키 테이블은 부분 종속 자체가 불가능하므로 자동으로 2NF를 만족한다."}]}', 780),

('c1000000-0000-0000-0000-000000000004', 12, 'BCNF', 'quiz', '{"questions":[{"question":"BCNF(보이스-코드 정규형)의 조건으로 올바른 것은?","code":null,"options":["모든 함수 종속에서 종속자가 후보키이어야 한다","모든 함수 종속에서 결정자가 후보키이어야 한다","이행적 종속이 없으면 자동으로 BCNF를 만족한다","복합 기본키가 없어야 한다"],"correct_index":1,"explanation":"BCNF는 3NF보다 강한 조건으로, X→Y인 모든 함수 종속에서 X(결정자)가 반드시 후보키이어야 한다. 3NF를 만족해도 결정자가 후보키가 아닌 경우 BCNF를 위반할 수 있다."},{"question":"다음 테이블에서 BCNF 위반이 발생하는 이유는?","code":"-- 테이블: 수강(학번, 과목명, 교수명)\n-- 후보키: (학번, 과목명), (학번, 교수명)\n-- 함수 종속:\n--   (학번, 과목명) → 교수명\n--   (학번, 교수명) → 과목명\n--   교수명 → 과목명  ← 주목","options":["학번이 후보키가 아니기 때문이다","교수명→과목명에서 교수명이 후보키가 아니기 때문이다","과목명에 중복 값이 있기 때문이다","이 테이블은 BCNF를 이미 만족한다"],"correct_index":1,"explanation":"교수명→과목명이라는 함수 종속이 존재하는데, 교수명 단독으로는 후보키가 아니다. BCNF는 모든 결정자가 후보키여야 하므로 이 경우 BCNF를 위반한다."},{"question":"3NF는 만족하지만 BCNF는 만족하지 않는 경우의 특징은?","code":null,"options":["이행적 종속이 존재할 때","후보키가 여러 개이고 복합 후보키들이 서로 겹치는 속성을 가질 때","기본키가 단일 속성일 때","NULL 값이 존재할 때"],"correct_index":1,"explanation":"후보키가 여러 개이며 복합 후보키들이 공통 속성을 공유할 때(중첩 후보키), 3NF는 만족하지만 BCNF를 위반하는 상황이 발생할 수 있다."},{"question":"BCNF 위반 테이블을 분해할 때 발생할 수 있는 문제는?","code":null,"options":["데이터 중복이 증가한다","무손실 분해가 불가능하다","일부 함수 종속 정보가 보존되지 않을 수 있다","분해 후 조인이 불가능해진다"],"correct_index":2,"explanation":"BCNF로 분해하면 무손실 분해는 보장되지만, 일부 함수 종속이 분해된 테이블에 표현되지 않아 종속성 보존이 안 될 수 있다. 이 경우 3NF와 BCNF 사이에서 트레이드오프가 발생한다."},{"question":"다음 중 BCNF 분해의 올바른 방법은?","code":"-- 수강 테이블: (학번, 과목명, 교수명)\n-- 위반 종속: 교수명 → 과목명","options":["(학번, 과목명) + (교수명)으로 분해","(교수명, 과목명) + (학번, 교수명)으로 분해","(학번, 과목명, 교수명)을 그대로 유지","(학번) + (과목명, 교수명)으로 분해"],"correct_index":1,"explanation":"위반하는 함수 종속 교수명→과목명을 별도 테이블로 분리한다. 교수과목 테이블(교수명, 과목명)과 수강 테이블(학번, 교수명)로 분해하면 BCNF를 만족한다."}]}', 780),

('c1000000-0000-0000-0000-000000000004', 13, 'ERD', 'flashcard', '{"cards":[{"front":"ERD(Entity-Relationship Diagram)란?","back":"데이터베이스의 논리적 구조를 시각적으로 표현한 다이어그램.\n\n구성 요소:\n- 개체(Entity): 직사각형\n- 관계(Relationship): 마름모\n- 속성(Attribute): 타원\n- 연결선: 개체와 관계를 연결\n\n데이터베이스 설계 단계에서 요구사항을 분석하고 구조화하는 데 사용된다.","hint":null},{"front":"ERD에서 카디널리티(Cardinality) 표기 방법은?","back":"두 개체 간 관계의 수적 제약을 나타냄:\n\n1:1 (일대일) - 한 개체가 다른 개체 하나와만 대응\n예: 직원 ↔ 사원증\n\n1:N (일대다) - 한 개체가 여러 개체와 대응\n예: 고객 ↔ 주문\n\nM:N (다대다) - 여러 개체가 여러 개체와 대응\n예: 학생 ↔ 수강과목","hint":"1:1, 1:N, M:N"},{"front":"강한 개체(Strong Entity)와 약한 개체(Weak Entity)의 차이는?","back":"강한 개체: 자체적으로 기본키를 가지고 독립적으로 존재 가능\n예: 고객(customer_id)\n\n약한 개체: 다른 개체에 의존하여 존재하며 자체 기본키가 없음\n예: 주문상세(주문번호+상품번호로 식별)\n\nERD에서 약한 개체는 이중 직사각형으로 표기한다.","hint":null},{"front":"ERD에서 속성의 종류는?","back":"단순 속성: 더 이상 분해 불가 (나이, 학번)\n복합 속성: 여러 단순 속성으로 구성 (주소 = 시+구+동)\n단일값 속성: 하나의 값만 가짐 (학번)\n다치 속성: 여러 값을 가짐 (전화번호 여러 개) - 이중 타원\n유도 속성: 다른 속성으로 계산 가능 (나이 ← 생년월일) - 점선 타원","hint":"단순/복합/단일/다치/유도"},{"front":"M:N 관계를 관계형 DB로 변환하는 방법은?","back":"M:N 관계는 직접 테이블로 표현할 수 없다.\n중간에 연결 테이블(Junction Table / Bridge Table)을 생성한다.\n\n예: 학생(M) ↔ 과목(N)\n→ 학생 테이블 + 과목 테이블 + 수강 테이블(학번, 과목코드)\n\n수강 테이블의 기본키는 (학번, 과목코드)의 복합키가 된다.","hint":"연결 테이블 생성"}]}', 660),

('c1000000-0000-0000-0000-000000000004', 14, '인덱스', 'quiz', '{"questions":[{"question":"인덱스(Index)를 사용하는 주요 목적은?","code":null,"options":["데이터 삽입 속도를 향상시키기 위해","데이터 검색 속도를 향상시키기 위해","저장 공간을 절약하기 위해","데이터 무결성을 보장하기 위해"],"correct_index":1,"explanation":"인덱스는 책의 색인처럼 특정 열의 값으로 행을 빠르게 찾을 수 있게 해주는 자료구조이다. SELECT 쿼리 성능을 향상시키지만, INSERT/UPDATE/DELETE 시 인덱스도 갱신해야 하므로 쓰기 성능은 저하될 수 있다."},{"question":"B-Tree 인덱스의 특징으로 올바른 것은?","code":null,"options":["등호(=) 검색에만 사용 가능하다","범위 검색(BETWEEN, >, <)과 등호 검색 모두 효율적이다","해시 인덱스보다 항상 빠르다","전체 텍스트 검색에 최적화되어 있다"],"correct_index":1,"explanation":"B-Tree(Balanced Tree) 인덱스는 트리 구조로 데이터를 정렬하여 저장한다. 등호 검색뿐 아니라 범위 검색도 효율적으로 지원한다. 해시 인덱스는 등호 검색만 지원하지만 더 빠를 수 있다."},{"question":"클러스터드 인덱스(Clustered Index)와 비클러스터드 인덱스의 차이로 올바른 것은?","code":null,"options":["클러스터드 인덱스는 테이블당 여러 개를 생성할 수 있다","클러스터드 인덱스는 실제 데이터 행이 인덱스 순서대로 물리적으로 정렬된다","비클러스터드 인덱스는 테이블당 하나만 생성 가능하다","비클러스터드 인덱스가 항상 더 빠르다"],"correct_index":1,"explanation":"클러스터드 인덱스는 테이블의 실제 데이터가 인덱스 키 순서대로 물리적으로 저장된다. 테이블당 하나만 존재 가능하며 보통 기본키에 설정된다. 비클러스터드 인덱스는 별도 구조에 저장되며 여러 개 생성 가능하다."},{"question":"다음 중 인덱스 사용이 효과적이지 않은 경우는?","code":"-- 어떤 쿼리에 인덱스가 비효율적인가?\nA) SELECT * FROM orders WHERE order_date = ''2024-01-01'';\nB) SELECT * FROM employees WHERE gender = ''M'';  -- 50% 비율\nC) SELECT * FROM products WHERE product_id = 1001;\nD) SELECT * FROM logs WHERE created_at BETWEEN ''2024-01-01'' AND ''2024-01-02'';","options":["A","B","C","D"],"correct_index":1,"explanation":"카디널리티(고유값 비율)가 낮은 열은 인덱스 효과가 떨어진다. gender처럼 M/F 두 가지 값만 있어 절반을 차지하면, 인덱스를 통해 읽어도 결국 전체의 절반을 스캔해야 하므로 Full Scan이 더 효율적일 수 있다."},{"question":"인덱스 생성 SQL과 그 설명으로 올바른 것은?","code":"CREATE INDEX idx_name ON students(name);\nCREATE UNIQUE INDEX idx_email ON members(email);\nCREATE INDEX idx_dept_age ON employees(department, age);","options":["UNIQUE INDEX는 NULL 값도 중복을 허용하지 않는다","복합 인덱스(idx_dept_age)는 department, age 어떤 순서로도 동일하게 효율적이다","UNIQUE INDEX는 해당 열에 중복 값 삽입을 방지한다","인덱스는 테이블과 별도의 데이터베이스에 저장된다"],"correct_index":2,"explanation":"UNIQUE INDEX는 인덱스 기능과 함께 해당 열의 유일성 제약 조건을 강제한다. 복합 인덱스는 선두 컬럼(department)이 조건에 포함될 때 가장 효율적이며, 순서가 중요하다."}]}', 720),

('c1000000-0000-0000-0000-000000000004', 15, '실행 계획', 'reading', '{"questions":[{"question":"다음 실행 계획에서 Full Table Scan이 발생하는 쿼리는?","code":"-- 테이블: products (100만 행)\n-- 인덱스: idx_product_id ON products(product_id)\n\n-- 쿼리 A\nSELECT * FROM products WHERE product_id = 5000;\n-- 실행 계획: Index Seek (idx_product_id)\n\n-- 쿼리 B\nSELECT * FROM products WHERE UPPER(name) = ''APPLE'';\n-- 실행 계획: Table Scan","options":["쿼리 A","쿼리 B","두 쿼리 모두","두 쿼리 모두 아님"],"correct_index":1,"explanation":"함수를 열에 적용하면(UPPER(name)) 인덱스를 사용할 수 없어 Full Table Scan이 발생한다. 인덱스는 원본 값 기준으로 생성되었는데 함수 변환 후 비교하므로 인덱스를 활용할 수 없다."},{"question":"실행 계획(EXPLAIN)을 분석할 때 주목해야 할 항목으로 가장 중요한 것은?","code":"-- MySQL EXPLAIN 예시\nEXPLAIN SELECT * FROM orders o\nJOIN customers c ON o.customer_id = c.customer_id\nWHERE o.status = ''pending'';\n\n-- 결과 컬럼: id, select_type, table, type, key, rows, Extra","options":["id 컬럼의 숫자","table 컬럼의 테이블명","type과 key 컬럼 - 접근 방식과 사용 인덱스","select_type 컬럼"],"correct_index":2,"explanation":"type 컬럼은 접근 방식(ALL=풀스캔, index=인덱스스캔, ref/eq_ref=인덱스 참조, const=상수 조회)을 보여주고, key는 실제 사용된 인덱스를 보여준다. 이 두 컬럼이 쿼리 성능 판단에 가장 중요하다."},{"question":"인덱스가 있어도 Full Scan이 발생하는 경우가 아닌 것은?","code":null,"options":["WHERE 절에서 열에 함수를 적용한 경우 (YEAR(created_at) = 2024)","LIKE ''%검색어%''처럼 앞에 와일드카드를 사용한 경우","기본키 열을 정확한 값으로 등호 검색하는 경우","조회 대상 행이 전체의 30% 이상인 경우"],"correct_index":2,"explanation":"기본키에 대한 정확한 등호 검색은 클러스터드 인덱스를 사용하는 가장 효율적인 방법이다. 나머지는 모두 인덱스를 무력화하거나 Full Scan이 더 효율적인 경우이다."},{"question":"쿼리 최적화 힌트(Query Hint)를 사용하는 상황으로 적절한 것은?","code":"-- 힌트 사용 예시 (MySQL)\nSELECT /*+ INDEX(orders idx_status) */ *\nFROM orders\nWHERE status = ''pending'';","options":["모든 쿼리에 기본으로 적용해야 한다","옵티마이저가 잘못된 실행 계획을 선택할 때 강제로 지정한다","인덱스가 없는 테이블에서 성능을 향상시킬 때 사용한다","JOIN을 UNION으로 변환할 때 사용한다"],"correct_index":1,"explanation":"쿼리 옵티마이저는 통계 정보를 기반으로 최적의 실행 계획을 자동 선택하지만, 간혹 잘못된 계획을 선택할 수 있다. 이때 힌트로 특정 인덱스나 조인 방법을 강제 지정할 수 있다."}]}', 720),

('c1000000-0000-0000-0000-000000000004', 16, '트랜잭션 ACID', 'flashcard', '{"cards":[{"front":"트랜잭션(Transaction)이란?","back":"데이터베이스에서 하나의 논리적 작업 단위를 구성하는 연산의 집합.\n\n모두 성공하거나(COMMIT) 모두 실패해야(ROLLBACK) 한다.\n\n예: 은행 이체 = 출금 + 입금 두 연산이 반드시 함께 성공해야 함.\n\nBEGIN → 작업 → COMMIT 또는 ROLLBACK","hint":null},{"front":"원자성(Atomicity)이란?","back":"트랜잭션의 모든 연산이 완전히 수행되거나, 하나라도 실패하면 전혀 수행되지 않은 상태로 되돌아가야 한다.\n\n''All or Nothing'' 원칙.\n\n예: 이체 중 오류 발생 시 출금도 취소되어야 함.\n\nROLLBACK으로 구현된다.","hint":"All or Nothing"},{"front":"일관성(Consistency)이란?","back":"트랜잭션 실행 전후로 데이터베이스가 항상 일관된 상태를 유지해야 한다.\n\n즉, 정의된 모든 무결성 제약 조건(기본키, 외래키, CHECK 등)을 만족해야 한다.\n\n예: 계좌 잔액이 음수가 되는 상태는 일관성 위반.","hint":"제약 조건 항상 만족"},{"front":"격리성(Isolation)이란?","back":"동시에 실행되는 여러 트랜잭션이 서로의 중간 결과에 영향을 주지 않아야 한다.\n\n각 트랜잭션은 마치 혼자 실행되는 것처럼 동작해야 한다.\n\n격리 수준(Isolation Level)으로 성능과 정합성 간 트레이드오프를 조절한다.","hint":"트랜잭션 간 독립성"},{"front":"지속성(Durability)이란?","back":"성공적으로 커밋된 트랜잭션의 결과는 시스템 장애(정전, 크래시 등)가 발생해도 영구적으로 보존되어야 한다.\n\nWrite-Ahead Logging(WAL), 트랜잭션 로그, 체크포인트 등으로 구현된다.\n\n커밋 후에는 어떤 상황에서도 데이터가 유지된다.","hint":"커밋 후 영구 보존"}]}', 600),

('c1000000-0000-0000-0000-000000000004', 17, '격리 수준', 'quiz', '{"questions":[{"question":"가장 낮은 격리 수준인 Read Uncommitted에서 발생하는 이상현상은?","code":null,"options":["Phantom Read","Non-repeatable Read","Dirty Read","Lost Update"],"correct_index":2,"explanation":"Dirty Read는 다른 트랜잭션이 아직 커밋하지 않은(변경 중인) 데이터를 읽는 현상이다. Read Uncommitted에서만 발생하며 가장 심각한 정합성 문제이다."},{"question":"다음 시나리오에서 발생하는 이상현상은?","code":"-- 트랜잭션 A\nT1: SELECT balance FROM account WHERE id=1; -- 결과: 1000\nT1: (다른 작업 중...)\n\n-- 트랜잭션 B (그 사이)\nT2: UPDATE account SET balance=2000 WHERE id=1;\nT2: COMMIT;\n\n-- 트랜잭션 A 계속\nT1: SELECT balance FROM account WHERE id=1; -- 결과: 2000 (다름!)","options":["Dirty Read","Non-repeatable Read","Phantom Read","Lost Update"],"correct_index":1,"explanation":"Non-repeatable Read는 같은 트랜잭션 내에서 같은 행을 두 번 읽었을 때 다른 트랜잭션의 커밋으로 인해 결과가 달라지는 현상이다. Read Committed 격리 수준에서 발생한다."},{"question":"Phantom Read가 발생하는 격리 수준은?","code":null,"options":["Read Uncommitted만 해당","Read Committed까지 해당","Repeatable Read까지 해당","Serializable에서도 발생"],"correct_index":2,"explanation":"Phantom Read는 같은 범위 조건으로 두 번 조회할 때 다른 트랜잭션의 INSERT/DELETE로 인해 행의 수가 달라지는 현상이다. Repeatable Read까지 발생하며, Serializable에서는 발생하지 않는다."},{"question":"Serializable 격리 수준의 특징으로 올바른 것은?","code":null,"options":["Dirty Read만 방지한다","모든 이상현상을 방지하지만 동시성이 가장 낮다","Non-repeatable Read만 방지한다","성능이 가장 좋다"],"correct_index":1,"explanation":"Serializable은 가장 높은 격리 수준으로 Dirty Read, Non-repeatable Read, Phantom Read를 모두 방지한다. 트랜잭션을 직렬적으로 처리하는 것과 동일한 결과를 보장하지만, 동시성이 가장 낮아 성능이 떨어진다."},{"question":"MySQL InnoDB의 기본 격리 수준은?","code":null,"options":["Read Uncommitted","Read Committed","Repeatable Read","Serializable"],"correct_index":2,"explanation":"MySQL InnoDB의 기본 격리 수준은 Repeatable Read이다. MVCC(Multi-Version Concurrency Control)를 통해 Phantom Read도 어느 정도 방지한다. PostgreSQL의 기본값은 Read Committed이다."}]}', 780),

('c1000000-0000-0000-0000-000000000004', 18, '락과 동시성', 'quiz', '{"questions":[{"question":"공유락(Shared Lock)과 배타락(Exclusive Lock)의 차이로 올바른 것은?","code":null,"options":["공유락은 읽기/쓰기 모두 차단하고, 배타락은 읽기만 허용한다","공유락은 여러 트랜잭션이 동시에 읽기 가능하고, 배타락은 다른 모든 접근을 차단한다","배타락은 여러 트랜잭션이 동시에 획득 가능하다","공유락이 배타락보다 더 강한 제한이다"],"correct_index":1,"explanation":"공유락(S-Lock)은 읽기 작업에 사용되며 여러 트랜잭션이 동시에 획득 가능하다. 배타락(X-Lock)은 쓰기 작업에 사용되며 다른 어떤 락과도 공존할 수 없어 독점적으로 사용된다."},{"question":"데드락(Deadlock)이 발생하는 조건은?","code":"-- 트랜잭션 A\nT_A: LOCK 자원1 획득\nT_A: LOCK 자원2 대기 중...\n\n-- 트랜잭션 B (동시에)\nT_B: LOCK 자원2 획득\nT_B: LOCK 자원1 대기 중...","options":["한 트랜잭션이 너무 많은 자원을 잠글 때","두 트랜잭션이 서로 상대방이 가진 자원을 기다릴 때","락 타임아웃이 너무 짧게 설정되었을 때","트랜잭션이 너무 오래 실행될 때"],"correct_index":1,"explanation":"데드락은 두 개 이상의 트랜잭션이 서로 상대방이 보유한 자원의 락을 기다리는 순환 대기 상태이다. 위 예시에서 A는 자원2를, B는 자원1을 영원히 기다리게 된다."},{"question":"데드락 해결 방법으로 올바르지 않은 것은?","code":null,"options":["타임아웃 설정 후 하나의 트랜잭션을 롤백한다","데드락 감지 후 희생자(victim) 트랜잭션을 선택하여 롤백한다","모든 트랜잭션이 자원을 같은 순서로 획득하도록 강제한다","락 대기 시간을 무한정으로 늘린다"],"correct_index":3,"explanation":"락 대기를 무한정 허용하면 데드락이 영원히 해결되지 않는다. 데드락 예방(자원 획득 순서 통일), 감지 후 롤백, 타임아웃이 일반적인 해결책이다."},{"question":"MVCC(Multi-Version Concurrency Control)의 특징으로 올바른 것은?","code":null,"options":["읽기 작업도 배타락을 사용한다","각 데이터의 여러 버전을 유지하여 읽기와 쓰기가 서로를 차단하지 않는다","쓰기 성능을 최우선으로 향상시킨다","단일 버전만 유지하여 저장 공간을 절약한다"],"correct_index":1,"explanation":"MVCC는 데이터의 여러 버전을 유지하여 읽기 트랜잭션이 쓰기 트랜잭션을 차단하지 않도록 한다. PostgreSQL, MySQL InnoDB가 이를 사용하며, 읽기 성능을 크게 향상시킨다."},{"question":"낙관적 락(Optimistic Lock)과 비관적 락(Pessimistic Lock)의 차이는?","code":null,"options":["낙관적 락은 트랜잭션 시작 시 즉시 락을 획득한다","낙관적 락은 충돌이 드물 것으로 가정하여 커밋 시에만 충돌을 검사한다","비관적 락은 락을 전혀 사용하지 않는다","낙관적 락은 항상 비관적 락보다 성능이 좋다"],"correct_index":1,"explanation":"낙관적 락은 충돌이 거의 없다고 가정하여 락 없이 작업 후 커밋 시 버전 번호나 타임스탬프로 충돌을 감지한다. 비관적 락은 충돌 가능성이 높다고 보고 작업 전에 락을 먼저 획득한다."}]}', 780),

('c1000000-0000-0000-0000-000000000004', 19, 'NoSQL 개념', 'flashcard', '{"cards":[{"front":"NoSQL이란 무엇이고 언제 사용하는가?","back":"Not Only SQL의 약자로 관계형 DB의 한계를 극복하기 위한 비관계형 데이터베이스.\n\n사용 상황:\n- 대용량, 고속 처리가 필요할 때\n- 스키마가 자주 변경될 때\n- 수평적 확장(Scale-out)이 필요할 때\n- 비정형/반정형 데이터 저장 시\n\n단점: 트랜잭션, 조인, 강한 일관성 지원 제한","hint":null},{"front":"Document DB란?","back":"데이터를 JSON/BSON 형태의 문서(Document)로 저장한다.\n\n특징:\n- 유연한 스키마 (필드가 문서마다 달라도 됨)\n- 중첩 구조 지원\n- 대표 제품: MongoDB, CouchDB\n\n사용 예: 사용자 프로필, 상품 카탈로그, 콘텐츠 관리 시스템","hint":"JSON 문서 저장"},{"front":"Key-Value DB란?","back":"단순한 키(Key)-값(Value) 쌍으로 데이터를 저장한다.\n\n특징:\n- 가장 단순한 NoSQL 모델\n- 매우 빠른 읽기/쓰기 성능\n- 복잡한 쿼리 불가\n- 대표 제품: Redis, Memcached, DynamoDB\n\n사용 예: 세션 저장, 캐싱, 실시간 랭킹","hint":"캐시에 많이 사용"},{"front":"Column-Family DB란?","back":"행 대신 열(컬럼) 중심으로 데이터를 저장한다.\n\n특징:\n- 관련 열을 묶어 Column Family로 관리\n- 대용량 데이터 쓰기에 최적화\n- 집계 쿼리 성능 우수\n- 대표 제품: Apache Cassandra, HBase\n\n사용 예: 시계열 데이터, 로그 분석, IoT 센서 데이터","hint":"열 중심 저장"},{"front":"Graph DB란?","back":"데이터를 노드(Node)와 간선(Edge)으로 표현한다.\n\n특징:\n- 관계가 복잡하게 연결된 데이터에 최적\n- 관계 탐색(최단 경로 등)이 빠름\n- 대표 제품: Neo4j, Amazon Neptune\n\n사용 예: SNS 친구 관계, 추천 엔진, 사기 탐지, 지식 그래프","hint":"관계 중심 저장"}]}', 660),

('c1000000-0000-0000-0000-000000000004', 20, 'DB 종합', 'quiz', '{"questions":[{"question":"다음 SQL의 실행 순서로 올바른 것은?","code":"SELECT department, AVG(score) AS avg_score\nFROM students\nWHERE score >= 60\nGROUP BY department\nHAVING AVG(score) >= 75\nORDER BY avg_score DESC;","options":["SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY","FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY","WHERE → FROM → GROUP BY → SELECT → HAVING → ORDER BY","FROM → SELECT → WHERE → HAVING → GROUP BY → ORDER BY"],"correct_index":1,"explanation":"SQL 논리적 실행 순서: FROM(테이블 참조) → WHERE(행 필터링) → GROUP BY(그룹화) → HAVING(그룹 필터링) → SELECT(열 선택 및 집계) → ORDER BY(정렬). 작성 순서와 실행 순서가 다르다."},{"question":"다음 중 데이터 무결성(Data Integrity) 유형과 그 설명이 잘못 연결된 것은?","code":null,"options":["개체 무결성: 기본키는 NULL이거나 중복될 수 없다","참조 무결성: 외래키는 참조 테이블의 기본키에 존재하는 값이어야 한다","도메인 무결성: 각 열의 값은 정의된 데이터 타입과 범위를 만족해야 한다","관계 무결성: 기본키 없이 외래키만 존재할 수 있다"],"correct_index":3,"explanation":"관계 무결성이라는 표준 용어는 없으며, 설명 자체도 틀렸다. 외래키가 있으려면 참조 대상 테이블의 기본키가 반드시 존재해야 한다. 나머지 개체/참조/도메인 무결성 설명은 모두 올바르다."},{"question":"트랜잭션 ACID 속성 중 시스템 장애 후 커밋된 데이터가 유지되는 것을 보장하는 속성은?","code":null,"options":["원자성(Atomicity)","일관성(Consistency)","격리성(Isolation)","지속성(Durability)"],"correct_index":3,"explanation":"지속성(Durability)은 커밋된 트랜잭션의 결과가 시스템 장애에도 영구적으로 유지됨을 보장한다. Write-Ahead Log(WAL) 등의 기법으로 구현된다."},{"question":"다음 중 3NF를 만족하는 테이블 구조는?","code":"A) 주문(주문번호, 고객번호, 고객이름, 상품번호, 수량)\nB) 주문(주문번호, 고객번호, 상품번호, 수량)\n   고객(고객번호, 고객이름)\nC) 주문(주문번호, 고객번호, 고객이름)\n   상세(상세번호, 상품번호, 수량)\nD) 통합(주문번호, 고객번호, 고객이름, 상품번호, 상품명, 수량, 가격)","options":["A","B","C","D"],"correct_index":1,"explanation":"B는 주문 테이블에서 이행 종속(주문→고객번호→고객이름)을 제거하여 고객 테이블로 분리했다. 각 테이블의 비키 속성이 기본키에만 완전 함수 종속되어 3NF를 만족한다."},{"question":"다음 인덱스 전략 중 올바르지 않은 것은?","code":null,"options":["자주 WHERE 절에 사용되는 열에 인덱스를 생성한다","카디널리티가 높은(고유값이 많은) 열이 인덱스 효과가 크다","모든 열에 인덱스를 생성하면 SELECT 성능이 극대화된다","복합 인덱스는 선두 컬럼이 조건에 포함될 때 가장 효율적이다"],"correct_index":2,"explanation":"인덱스를 과도하게 생성하면 INSERT/UPDATE/DELETE 시 모든 인덱스를 갱신해야 하므로 쓰기 성능이 크게 저하된다. 또한 저장 공간도 추가로 소비된다. 꼭 필요한 열에만 선택적으로 인덱스를 생성해야 한다."}]}', 780);
